apiVersion: v1
kind: Pod
metadata:
  name: orderservice
  labels:
    app: pizzaorders
spec:
  hostname: idp
  containers:
  - name: pizzaorder
    image: pizzatime.orderservice:latest
    imagePullPolicy: Never
    env:
        - name: amqp.host
          value: brokerservice.default.svc.cluster.local
        - name: amqp.username
          value: guest 
        - name: amqp.password
          value: guest
        - name: server.port 
          value: "8080"
    resources:
      limits:
        memory: "2Gi"
        cpu: "500m"
    ports:
      - name: httpservice
        containerPort: 8080

  - name: database
    image: docker.io/mysql
    ports:
    - name:  database
      containerPort: 3306
    resources:
      limits:
        cpu: "500m"
        memory: 2Gi
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: root
      - name : MYSQL_DATABASE
        value: pizzaorders
      - name: MYSQL_TCP_PORT
        value : "3306"

    volumeMounts:
    - name:  database-volume
      mountPath: /var/lib/mysql
    
  volumes:
  - name:  database-volume
    persistentVolumeClaim:
      claimName: ord-pvc
  restartPolicy: OnFailure


---

apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: ClusterIP
  selector:
    app: pizzaorders
  ports:
  - port: 8080
    targetPort: 8080
