apiVersion: v1
kind: Pod
metadata:
  name: pizzaidp
  labels:
    name: pizzaidp
spec:
  hostname: pizzaidp
  containers:
  - name: pizzaidp
    image: pizzatime.idp:latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: httpservice
        containerPort: 8080

  - name: database
    image: docker.io/mysql
    ports:
    - name:  database
      containerPort: 3306
    resources:
      limits:
        cpu: "50m"
        memory: 2Gi
      requests:
        cpu: "50m"
        memory: 1Gi
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: root
#    volumeMounts:
#    - name:  database-volume
#      mountPath: /var/lib/mysql
    
#  volumes:
#  - name:  database-volume
#    hostPath:
#      path: ./data/mysql
#      type: DirectoryOrCreate
  restartPolicy: Always


