apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzaidp
spec:
  selector:
    matchLabels:
      app: pizzaidp
  template:
    metadata:
      labels:
        app: pizzaidp
    spec:
      containers:
      - name: pizzaidp
        image: pizzatime.pizzaidph2:latest
        imagePullPolicy: Never
        env:
            - name: amqp.host
              value: brokerservice.default.svc.cluster.local
            - name: amqp.username
              value: guest 
            - name: amqp.password
              value: guest
            - name: server.port 
              value: "8080"
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
          - name: httpservice
            containerPort: 8080

      - name: database
        image: docker.io/mysql
        ports:
        - name:  database
          containerPort: 3306
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name : MYSQL_DATABASE
            value: pizzaidpdatabase
          - name: MYSQL_TCP_PORT
            value : "3306"
        volumeMounts:
        - name:  database-volume
          mountPath: /var/lib/mysql

      volumes:
      - name:  database-volume
        persistentVolumeClaim:
          claimName: idp-pvc


---

apiVersion: v1
kind: Service
metadata:
  name: idp-service
spec:
  type: ClusterIP
  selector:
    app: pizzaidp
  ports:
  - port: 8080
    targetPort: 8080
